#!/usr/bin/env bash

# Alt. script to shell alias (in compo-inc), which are not usually turned on in
# a shell. Sourced as well by ~/.alias to use this function for the alias, so
# the implementation is exactly the same.

composure_load='. ~/.local/composure/Composure/load.inc && c-load'

# Define main handler func
COMPO_CMD="$composure_load;"' "$@"'
composure_run () {
  local COMPO_CMD="${COMPO_CMD}"
  test "${DEBUG:-0}" = "0" || COMPO_CMD="set -x;$COMPO_CMD"
  test -n "${shell_f-}" || {
    test "${interactive:-0}" = 0 || shell_f=i
    test "${login:-0}" = 0 || shell_f=${shell_f-}l
  }
  $LOG note "" "composure-inc:" "$COMPO_CMD $*"
  ${shell:-"bash"} -${shell_f-}c "$COMPO_CMD" composure-inc: "$@"
}

composure_run_seq () {
  composure_run c-main-seq "$@"
}

# Execute
case "$0" in

    */compo-seq ) v=${v=4} composure_run_seq "$@" ;;

    */compo ) v=${v=4} composure_run "$@" ;;

esac
