#!/bin/sh
uname=$(uname)

case "$uname" in

  Darwin )
      esc=`echo '\033'`
    ;;

  Linux | CYGWIN_NT-6.1 )
      # For GNU sed: \o033
      esc=`echo -e '\o33'`

      case "$(sed --version)" in *"This is not GNU sed"* )
              # For matchbox sed
              esc=`echo -e '\033'`
          ;;
      esac
    ;;

  * ) error "No stdio-type for $uname" 1 ;;
esac


case "$1" in

    graffiti ) f=$1 ; shift
            figlet -kf $f "$@" | sed -E '
    s/[<>Y()]/'$esc'[1;36m&'$esc'[0m/g
    s/[\/_]/'$esc'[1;30m&'$esc'[0m/g
    s/[\|\\]/'$esc'[0;36m&'$esc'[0m/g
    s/[\.]/'$esc'[1;37m&'$esc'[0m/g '
        ;;

    alligator | alligator2 ) f=$1 ; shift
            figlet -kf $f "$@" | sed -E '
    s/:/'$esc'[1;36m&'$esc'[0m/g
    s/\+/'$esc'[1;32m&'$esc'[0m/g
    s/\#/'$esc'[1;33m&'$esc'[0m/g '
        ;;

    sblood | poison ) f=$1 ; shift
            figlet -f $f "$@" | sed -E '
    s/@/'$esc'[1;31m@'$esc'[0m/g
    s/!/'$esc'[0;31m!'$esc'[0m/g
    s/[.:]/'$esc'[0;35m&'$esc'[0m/g
  '
        ;;

    chunky ) shift
            figlet -f chunky "$@" | sed -E '

    s/_/'$esc'[0;31m_'$esc'[0m/g
    s/\//'$esc'[0;33m\/'$esc'[0m/g
    s/\\/'$esc'[0;34m\\'$esc'[0m/g
    s/~/'$esc'[0;35m\~'$esc'[0m/g
  '
        ;;

    relief ) shift
            figlet -f relief "$@" | sed -E '
    s/_/'$esc'[1;30m_'$esc'[0m/g
    s/\//'$esc'[0;32m\/'$esc'[0m/g
    s/\\/'$esc'[0;34m\\'$esc'[0m/g
    s/~/'$esc'[0;37m\~'$esc'[0m/g
  '
        ;;

esac
