#!/bin/sh

## ImageMagick helpers

#shellcheck disable=SC1090,1007


scale () # ~ <Resolution> <Input> [<Output>]
{
  #shellcheck disable=SC2086
  convert "$2" -resize $1^ -gravity center -extend $1 "$3"
}

crop () # ~ <Geometry> <Input> [<Output>]
{
  convert "$2" -crop "$1" "$3"
}


test -n "${user_scripts_loaded:-}" || {
  . "${US_BIN:-"$HOME/bin"}"/user-scripts.sh
  user_scripts_loadenv
}

# Parse arguments
! script_isrunning "image" || eval "set -- $(user_script_defarg "$@")"

# Execute argv and return
script_defcmd="" script_entry "image" "$@"
#
