#!/usr/bin/env python

import sys

from script_mpe import confparse
from script_mpe.res import js
from script_mpe.confparse import yaml_load, yaml_dump, yaml_safe_dump


for f in sys.argv[1:]:
	data = js.load(open(f))
	print yaml_safe_dump(data)

