#! /usr/bin/env python

import argparse
import keyring
import getpass
import sys

def get_value(service, username):
    print keyring.get_password(service, username)

def set_value(service, value, username):
    keyring.set_password(service, username, value)

def delete_value(service, username):
    keyring.delete_password(service, username)

parser = argparse.ArgumentParser(
    usage="keychain [arg] arg\n\
       get, set and delete values in keychain", prog="keychain 0.1.2")

parser.add_argument('-g', dest="get", action='store', nargs='+', help='get a value, args: \
    <service> [username|$USER]')
parser.add_argument('-s', dest="set", action='store', nargs='+', help='save a value, args: \
    <service> <value> [username|$USER]')
parser.add_argument('-d', dest="delete", action='store', nargs='+', help='delete a value, args: \
    <service> [username|$USER]')

if len(sys.argv)==1:
    parser.print_help()
    sys.exit(1)

opts = parser.parse_args()

if opts.get is not None:
    if len(opts.get) == 1:
        username = getpass.getuser()
    else:
        username = opts.get[1]
    get_value(opts.get[0], username)
elif opts.set is not None:
    if len(opts.set) == 1:
        print parser.prog + ': error: missing value to set'
        exit(1)
    elif len(opts.set) == 2:
        username = getpass.getuser()
    else:
        print opts.set[0]
        username = opts.set[2]
    set_value(opts.set[0], opts.set[1], username)
elif opts.delete != None:
    if len(opts.delete) == 1:
        username = getpass.getuser()
    else:
        username = opts.delete[1]
    delete_value(opts.delete[0], username)
else:
    print "usage: keychain -h"
