#!/usr/bin/env bash

# Helper script to display some data derived from 'uptime' output

# Added Bash-optimized solutions and functions later, but kept original more
# practical pipeline approach to compare. Benchmarking shows removing sed/tr/cut
# pipelines is not an enormous speedup (probably because there still is some
# output capture going on) but does improve runtime even for these simple cases.

loadavg_parts ()
{
  local uptime
  read -r uptime <<< "$(uptime)"
  : "${uptime//* load average: }"
  : "${_//,}"
  read _1 _2 _3 <<< "$_"
}

loadavg () # ~ [<Index>] # Show 1, 5 or 15min average
{
  test $# -gt 0 && set -- _${1:?} || set -- _1
  local _1 _2 _3
  loadavg_parts
  echo "${!1}"
}

# select smallest period with loadvg above value, or display 15min avg.
# uptime must be reported and specified using exactly two decimals.
high_load () # ~ [<Value=<max>>]
{
  local _1 _2 _3
  loadavg_parts
  test $# -gt 0 || set -- $(max $_1 $_2 $_3)
  for _i in _1 _2 _3
  do
      : "${!_i}"
      test ${1/.} -le ${_/.} >/dev/null && break || continue
  done
  : "${_i/_/load_p}"
  : "${!_}"
  : "${_/in}"
  echo "${!_i}(${_})"
}

max ()
{
  local h=${1:?}
  shift; while test $# -gt 0; do
      test ${h/.} -gt ${1/.} || h=${1:?}
      shift
    done
  echo $h
}

load_p1=1min
load_p2=5min
load_p3=15min

case "$1" in

  # Show pretty uptime but make it as short as possible
  p|p2 )
      read -r uptime <<< "$(uptime -p)"
      : "${uptime//up /}"
      : "${_// minute/m}"
      : "${_// hour/h}"
      : "${_// day/d}"
      : "${_// week/w}"
      : "${_// month/mo}"
      : "${_// year/y}"
      : "${_//s}"
      : "${_//,}"
      echo "$_"
    ;;
  p1 )
      uptime -p | sed '
              s/^up //
              s/ minutes\?/m/
              s/ hours\?/h/
              s/ days\?/d/
              s/ weeks\?/w/
              s/ months\?/mo/
              s/, //g
          '
    ;;

  hl|high-load ) shift; high_load "$@" ;;

  l|l1 ) # get the requested loadavg part: , default 5min avg
      test $# -gt 1 || set -- "$1" 1
      echo $(uptime | sed 's/^.* load average: //' | tr -d ',' | cut -d' ' -f$2)
    ;;
  l2 ) shift; loadavg "$@" ;;

  g )
      # Select group from regular uptime output: 1: days/hours up; 2: users; 3: load avgs
      # TODO: move to shell profile export, test with tmux
      test $# -gt 1 || set -- "$1" 1
      echo $(uptime | sed '
        s/^.*\(up .*\),\ *\([0-9]*\ user[s]*\).*load[^0-9]*\(.*\)$/\'${2:?}'/
        s/ //g
      ')
    ;;

  help|--help|-h ) grep -Po '^ * [a-z0-9|-]* \)' "$0" ;;
  * ) echo "No such action '$1'?" >&2;
      exit 2 ;;
esac

# Id: US-Bin.mpe less-uptime [2015-2023]
