#!/usr/bin/env python
"""
Readline rename
"""
import os
import sys

from lib import Prompt


argv = list(sys.argv)
scriptname = argv.pop(0)
if not argv:
    sys.exit(1)
filename = argv.pop()
print filename

ok = False
while not ok:
    newfilename = Prompt.input('Filename: ', filename)
    print 'Going to rename %r to %r' % (filename, newfilename)
    ok = Prompt.ask('Ok?')
#os.rename(filename, newfilename)

