#!/bin/sh
# Created: 2016-04-03

set -e


main_entry()
{
  local scriptpath=$HOME/bin
  . $scriptpath/os.lib.sh
  rotate_file "$@" || return
}


test "$(basename $0)" = "rotate-file" && {
  main_entry $@ || exit $?
}
