#!/bin/sh
# Created: 2016-04-03

set -e


abbrev_rename()
{
    while read oldpath junk newpath
    do
        local idx=1
        while test "$(echo "$oldpath" | cut -c 1-$idx )" = "$(echo "$newpath" | cut -c 1-$idx )"
        do
            idx=$(( $idx + 1 ))
        done
        local end=$(( $idx - 1 ))
        echo "Backed up path: $(echo $oldpath | cut -c 1-$end){$(echo $oldpath | cut -c $idx-) => $(echo $newpath | cut -c $idx-)}"
    done
}

main_entry()
{
  test -e  "$1" || return 20
  local base=$(basename $@) \
    dir=$(dirname $1) \
    cnt=1
  while test -e "$dir/$base-$cnt$2"
  do
    cnt=$(( $cnt + 1 ))
  done
  { mv -v "$1" "$dir/$base-$cnt$2" || return $?; } | abbrev_rename 
}


test "$(basename $0)" = "rotate-file" && {
  main_entry $@ || exit $?
}


