#!/usr/bin/env bash

. "tools/ci/before-install.sh"
. "tools/ci/install.sh"

. "tools/ci/before.sh"

if . "tools/ci/script.sh"
then sh_ci_script_status=0; fi

. "tools/ci/before-cache.sh"

if test $sh_ci_script_status -eq 0
then
  TRAVIS_TEST_RESULT=1
  . "tools/ci/after-success.sh"
else
  TRAVIS_TEST_RESULT=0
  . "tools/ci/after-failure.sh"
fi

. "tools/ci/after.sh"

ci_announce "$scriptname OK"
# Sync: U-S:
# Id: script-mpe/ sh-ci vim:ft=bash:nowrap:
