#!/usr/bin/env bash
set -euo pipefail

CWD="$PWD"
PPWD="`pwd -P`"

unset  U_S  LOG  INIT_LOG  SCRIPTPATH

base=sh-composure

export UC_LOG_LEVEL=7
LOG=/etc/profile.d/uc-profile.sh

#test -n "${PROJECT_DIR:-}" || {
#  test -w /srv/project-local &&
#    PROJECT_DIR=/srv/project-local || PROJECT_DIR=$HOME/project
#}

#U_S=/src/github.com/dotmpe/user-scripts
#: "${U_S:="$HOME/build/dotmpe/user-scripts"}"
: "${U_S:="$HOME/project/user-scripts"}"
#: "${LOG:="$PPWD/tools/sh/log.sh"}"
: "${LOG:="$U_S/tools/sh/log.sh"}"
#: "${INIT_LOG:="$LOG"}"

scriptpath=$CWD
SCRIPTPATH=

. $scriptpath/tools/sh/env.sh

. $scriptpath/tools/sh/init-include.sh

sh_include env-ucache env-0 env-log-reinit env-std env-dev env-test std-ci-helper \
    print-color

#. "tools/ci/util.sh"
#
#. "tools/ci/parts/init-user-repo.sh"

. "tools/sh/parts/env-scriptpath-deps.sh"
echo '-----'
echo $SCRIPTPATH | tr ':' '\n'

exit $?

. $PPWD/tools/sh/init.sh
lib_load composure str-htd std src function functions ck shell git volume oil docker-sh
lib_init

export_stage "$base"

ci_announce '---------- Listing user checkouts'
$U_S/bin/u-s user-repos
echo

#export  U_S  LOG  INIT_LOG
export verbosity=7

note OK


composure_check_name_scripts
#oil_docker_init


for lib in src/sh/lib/*.lib.sh
#for lib in src/sh/lib/function.lib.sh
do
  basename $lib .sh
  functions_list $lib | cut -d'(' -f1 | while read fn
  do
    function_linerange "$fn" "$lib" || return $?
    last_line=
    #echo "$start_line ($span_lines) to $end_line"

    grep_to_last '^\s*#' "$lib" "$end_line" && {
      echo found $lib $fn func annotation trailer until $last_line

      func_shaid=$(tail -n +$start_line $lib | head -n $span_lines | ck_sha1 -)

      annotation_span_lines=$(( $last_line - $end_line ))
      tail -n +$end_line $lib | head -n $annotation_span_lines |
        parse_func_annotation
      echo "# $func_shaid"
      continue

      span_lines=$(( $last_line - $start_line ))
      tail -n +$start_line $lib | head -n $span_lines

    } || true

  done
done
exit $?

copy_function  copy_function  src/sh/lib/function.lib.sh | ck_sha1 -
#| oshc deps
exit $?

# XXX composure_lib_load
#composure_lib_init
#composure_check_name_scripts
#composure_draft

echo 'add_env_path_lookup   src/sh/lib/sys.lib.sh
remove_env_path_lookup      src/sh/lib/sys.lib.sh
copy_function               src/sh/lib/function.lib.sh
' |  composure_shlib_sync_pairs

# Sync: U-S: vim:ft=bash:
