#!/usr/bin/env bash

# Build project{,-repo}-stats for github repositories

set -e

export verbosity=7

U_S=

test -e "$(realpath "/srv/project-local/")" && {

  : "${U_S:="/srv/project-local/user-scripts"}"
} || {

  test -d "/src/github.com/dotmpe" && {

    : "${U_S:="/src/github.com/dotmpe/user-scripts"}"
  } || {

    : "${U_S:="$HOME/build/dotmpe/user-scripts"}"
  }
}

: "${LOG:="$U_S/tools/sh/log.sh"}"

export U_S LOG

SCRIPTPATH=$U_S/src/sh/lib:$HOME/bin:$HOME/.conf/script
SCRIPTPATH=$SCRIPTPATH:$HOME/bin/commands:$HOME/bin/contexts
SCRIPTPATH=$SCRIPTPATH:$HOME/project/user-scripts-incubator/script/lib
export SCRIPTPATH

#export GITHUB_TOKEN=

exec $U_S/tools/sh/init-here.sh "$SCRIPTPATH" "" "" "$(cat <<EOM

  note "Initialized, loading more libs..."

  lib_load github htd date
  lib_init

  #lib_load build package build-test
  #package_init
  #build_test_init

  note "OK"

  github_repo_list | tr '/' ' ' | while read ns_name repo
  do
    echo \$repo:
    echo github_release_list "\$ns_name" "\$repo"
  done

  note "Done"
EOM
)"

# Sync: U-S: vim:ft=bash:
