#!/bin/sh

#tools/sh/init.sh
#tools/sh/init-here.sh
#tools/sh/log.sh
#tools/sh/tags-filter.sh
#tools/sh/tags.sh

#$(echo tools/ci/parts/*.sh)

for x in `cat <<EOM
tools/sh/boot/null.sh
tools/sh/boot/script.sh
tools/sh/boot/std.sh
tools/sh/boot/stderr-console-logger.sh
tools/sh/boot/test.sh
tools/sh/build/dev.sh
tools/sh/build/test.sh
tools/sh/parts/env-0.sh
$(echo tools/sh/parts/env-*.sh)
tools/sh/parts/init.sh
tools/sh/parts/print-color.sh
tools/sh/bats-colorize.sh
tools/sh/run.sh
tools/sh/util.sh
$(echo tools/ci/*.sh)
tools/sh/user-env.sh
tools/sh/env.sh
tools/ci/env.sh
EOM
`; do
  test -n "$x" || continue

  test -e ~/bin/$x -o -e ~/htdocs/$x \
      -o -e ~/project/user-scripts/$x \
      -o -e ~/project/user-scripts-incubator/$x || {

    echo "# No such file '$x'" >&2
    exit 100
  }
  echo "# x:'$x'" >&2

  #test -e ~/bin/$x -o -e ~/htdocs/$x  \
  #    -o -e ~/user-scripts/$x || touch ~/bin/$x

  diff -bqr ~/bin/$x ~/project/user-scripts/$x && continue

  vimdiff ~/"bin/$x" ~/"project/user-scripts/$x" ~/"htdocs/$x"
done
