#!/bin/bash

. ~/.bash_profile || { echo "No bash-profile" >&2; exit 100; }

BASHER_FULL_CLONE=true basher install dotmpe/user-scripts 
export U_S="$(basher package-path dotmpe/user-scripts)/"
cd "$U_S"
git checkout r0.0

cd /src/github.com/dotmpe/oil && \
make configure &&
build/dev.sh minimal

. $U_S/tool/sh/init.sh

$LOG notice $(basename $0) "Success!"
#lib_load std
#std_note "Success!"

# Sync: U-S: vim:ft=bash:
