#!/usr/bin/env bash

# Treebox for U-s
#
# Usage: ./sh-treebox-us [TAB-File [Line-Glob] | CMD]
#
# Default runs '$scriptname.tab' 'true;*/$scriptname-inner'.
#
# To run all scriptlines from table simply pass table file, or '*'
# as second argument.

set -o errexit
set -o pipefail
set -o nounset
scriptname="sh-treebox-us"
PPWD="`pwd -P`"

run()
{
  #echo "%supergroup  ALL=NOPASSWD:ALL" >.etc-sudoers.d-treebox-supergroup
  #  -v $PPWD/.etc-sudoers.d-treebox:/etc/sudoers.d/treebox-supergroup \
  dckr_u_s=/home/treebox/build/dotmpe/user-scripts
  dckr_u_s=/src/github.com/dotmpe/user-scripts

  docker run \
    -ti --rm \
    -v ~/.ssh:/home/treebox/.ssh:ro \
    -v ~/bin:/home/treebox/bin \
    -v $PPWD:$dckr_u_s \
    -v $(realpath /etc/localtime):/etc/localtime \
    -v $(realpath /srv/scm-git-24-2-notus-brix/):/srv/scm-git-24-2-notus-brix/ \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -u treebox \
    -w $dckr_u_s \
    "${sh_treebox_img}" "$@" </dev/tty
}

# Default is to run $scriptname suite scriptlines from table
test $# -gt 0 || set -- $scriptname.tab "true;*/$scriptname-inner"

test -n "$1" || {
  test $# -eq 2 -a "$2" = "*" && set -- "$scriptname.tab" "$2"
}
  
. "./tool/sh/part/print-color.sh"
CWD=$PWD U_S=$PWD . "./tool/sh/part/env-0.sh"

docker pull ${sh_treebox_img:="dotmpe/sandbox:dev"}

test ! -e "$PWD"/"$1" && {
  print_yellow "" "Running '$*'..."
  run "$@" &&
    print_green "OK" "Treebox U-s '$*'" ||
    print_red "Not OK: $?" "Treebox U-s '$*'"

} || {
  test $# -eq 2 || set -- "$1" "*"

  U_S=/srv/project-local/user-scripts
  . "$U_S/tool/ci/part/std-stack.sh"
  . "$U_S/tool/ci/part/std-runner.sh"

  sh_spec "$1" | grep -v '^\s*\(#.*\|\s*\)$' | while read scriptline
  do
    fnmatch "$2" "$scriptline" || continue

    print_yellow "" "Running '$scriptline'..."
    run sh -c "$scriptline" &&
      print_green "OK" "Treebox U-s '$scriptline'" ||
      print_red "Not OK: $?" "Treebox U-s '$scriptline'"
  done
}

# Sync: U-S: vim:ft=bash:
