#!/bin/bash

. ~/.bash_profile || { echo "No bash-profile" >&2; exit 100; }

BASHER_FULL_CLONE=true basher install bvberkum/user-scripts 
export U_S="$(basher package-path bvberkum/user-scripts)/"
cd "$U_S"
git checkout r0.0

cd /src/github.com/bvberkum/oil && \
make configure &&
build/dev.sh minimal

. $U_S/tools/sh/init.sh

$LOG notice $(basename $0) "Success!"
#lib_load std
#std_note "Success!"
