#!/usr/bin/env bash


current()
{
  true
}


# test $# -gt 0 -a "${1:-}" = "tasks

#|| set -- tooling-baseline

test $# -gt 0 || set -- current

echo tasks

whishlist-grep()
{
  grep -srI 'Would\ ' "$@"
}

whishlist-grep \
  cabinet/ \
  personal/

echo '--------'

whishlist-grep \
  cabinet/ \
  personal/

echo '--------'

# vim:ft=bash:
