#!/usr/bin/env bash

us-env -r user-script || ${us_stat:-exit} $?

! script_isrunning "system-tools" || {
  ALIASES=1 user_script_shell_mode
}


### User tools for OS and system

# Stuff that doesnt fir or categorize into other system-* scripts or user-*

host ()
{
  local actdef=--summary lkn=add; sa_a1_act_lk
  case "$act" in

  ( --diag ) TODO
    ;;

  ( --init )
      : about '(Re)build all reports'

      lib_require ctx-system htd-box || return
      us_part --alias uc-cache uc-command || return

      #: "${UC_HOST_SHARE:=${STATUSDIR_SHARE:?}/host,system,tools,share.bash}"
      : "${UC_HOST_LOCAL:=${STATUSDIR_LOCAL:?}/host,system,tools,local.bash}"
      : "${UC_HOST_CACHE:=${STATUSDIR_CACHE:?}/host,system,tools,cache.bash}"
      #: "${UC_HOST_LOG:=${STATUSDIR_LOG:?}/host,system,tools.log}"
      cache_loadmaps "$UC_HOST_LOCAL" uc_host_{{name,}id,stat,entry} || return
      [[ ! -s "$UC_HOST_CACHE" ]] || . "$UC_HOST_CACHE" || return

      local -n eid='uc_host_nameid["$OS_HOSTNAME"]'
      [[ ${eid-} ]] || {
        newid uc_host_nameid eid
        echo "uc_host_nameid[\"$OS_HOSTNAME\"]=$eid" >> "$UC_HOST_CACHE"
        uc_host_id[eid]=
        echo "uc_host_id[$eid]=$OS_HOSTNAME" >> "$UC_HOST_CACHE"
      }
      local -n stat='uc_host_stat["$eid"]'
      local -n entry='uc_host_entry["$eid"]'
     
      # TODO: Manage box via host.tab, add all hardware components,
      # get domains, and prepare for other conig and script provisioning
      htd_box_host --init stat entry
    ;;

  ( --summary ) TODO
    ;;

  ( * ) $LOG error "$lk" "No such action" "$act" ${_E_nsa:-68}
  esac
}

sdmmc_init ()
{
  #local sys{blk,dev} cid
  : "${sdmmc:=mmcblk0}"
  : "${sysblk:=/sys/block/${sdmmc:?}}"
  : "${sysdev:=${sysblk:?}/device}"
}

sdmmctab__libs=blocktab
sdmmctab__hooks=lib_init,sdmmc_init
sdmmctab ()
{
  local actdef='current' n='sdmmctab'; sa_a1_act_nlk
  case "$act" in

  ( entry ) # ~ ~ [<CId>]
    local cid=${1:-}
    if_ok "${cid:=$( < $sysdev/cid )}" &&
    # IIRC the last two chars (31 & 32) are derived otherwise from reader apparatus?
    grep ${grep_f:-} '\ \<'${cid:0:30}'[0-9a-f]*\>\ SD\ ' ${sdmmctab:?}
  ;;

  ( exists ) # ~ ~ [<CId>]
    grep_f=-q sdmmctab entry "$@"
  ;;

  ( current ) # ~ ~ [<CId|Num>]
    #sdmmctab entry "$@"
    sdmmctab load "$@" &&
    local k v &&
    for k in nr cid type size manfid date oemid hwrev name serial
    do v=sdmmc_${k:?} &&
      echo "$k: ${!v:--}"
    done
    grep " SD:${sdmmc_nr:?} " "${burnlog}"
  ;;

  ( current-raw )
      : "${sysdev:?}" &&
      echo "${sdmmc_nr:--} "$(cat $sysdev/cid) $(cat $sysdev/type) \
$(cat $sysblk/size) \
$(cat $sysdev/manfid) \
$(cat $sysdev/date) \
$(cat $sysdev/oemid) \
$(cat $sysdev/hwrev) \
$(cat $sysdev/name) \
$(cat $sysdev/serial)
  ;;

  ( init )
    sdmmctab exists || sdmmctab new
  ;;

  ( load ) # ~ ~ [<CId>]
    sdmmctab_entry="$(sdmmctab entry "$@")" &&
    <<< "$sdmmctab_entry" \
    read -r sdmmc_{nr,cid,type,size,manfid,date,oemid,hwrev,name,serial}
  ;;

  ( new )
    if_ok "$(sdmmctab current-raw)" &&
    echo "$_" | tee -a ${sdmmctab:?}
  ;;

  ( verify )
    local tab cur
    tab=$(sdmmctab entry) &&
    cur=$(sdmmctab current-raw) &&
    test "${tab#* }" = "${cur#* }" &&
    $LOG info "$lk" "OK" "$tab" ||
    $LOG error "$lk" "No match" "$cur" 1
  ;;

  ( * ) sa_E_nsact
  esac
}

newid ()
{
  local -n _newid_data=$1 _newid_var=$2
  _newid_var=$RANDOM
  while [[ ${_newid_data[$_newid_var]:+set} ]]
  do
    _newid_var=$RANDOM
  done
}

system_tools_loadenv ()
{
  #sh_mode strict &&
  user_script_loadenv &&
  #lk=":loadenv"
  user_script_initlog &&
  user_script_baseless=true \
  script_part=${1#system[_-]tools[_-]} user_script_load groups &&
  true # lib_load nerdfonts && lib_init nerdfonts
}


# Main entry (see user-script.sh for boilerplate)

! script_isrunning "system-tools" || {
  user_script_load || exit $?
  # Pre-parse arguments
  script_defcmd=short
  user_script_defarg=defarg\ aliasargv
  eval "set -- $(user_script_defarg "$@")"
}

# Execute argv and return
script_entry "system-tools" "$@"
#
