#!/usr/bin/env bash

### Helper to dislay (short) system status, for use in status bars


status ()
{
  echo "$(tmux-uptime l 2) $(systemd-short) $(tmux-uptime p)"
  # XXX: setup generic mail check
}

## New e-mails

# Count new e-mails (simple impl. for mutt with maildirs only).
# User-config must exist or else nothing is done.
emails ()
{
  emails-user-conf || return 0
  mutt-indicator
}

# Idem to emails however show new-mail counter as well
emails-count ()
{
  emails-user-conf || return 0
  mutt-indicator-count
}

emails-user-conf ()
{
  mutt-user-conf
}

# User mail-folder must be configured and maildir with inbox must exist.
mutt-user-conf ()
{
  test $# -gt 0 || set -- ${MUTTRC:-"$HOME/.muttrc"}
  local folder
  folder=$(eval "echo $(grep '^set folder=' $1 | sed 's/.*"\([^"]*\)"$/\1/')")
  test -e $folder/new
}

# Show email indicator if any new mail has been delivered
mutt-indicator ()
{
  mutt-new || return 0
  printf $nf_mdi_email_outline
}

mutt-indicator-count ()
{
  local count=$(mutt-count-new | awk '{sum+=$1} END{print sum;}')
  test ${count:-0} -eq 0 && return
  printf $nf_mdi_email_outline
  # XXX: this seems to be two characters wide? Messes up entire tmux screen.
  #printf $nf_mdi_email_variant
  printf ' '
  printf $count
}

mutt-new ()
{
  test -n "$(count_first=1 mutt-count-new)"
}

mutt-count-new ()
{
  local inb
  for inb in $(mutt-inboxes)
  do
    test -d "$inb/" || continue
    count=$(find $inb -mindepth 1 -maxdepth 1 | wc -l)
    test $count -eq 0 && continue
    echo "$count $inb"
    test ${count_first:-0} -eq 0 || return 0
  done
}

mutt-inboxes () # ~ muttrc-mail-
{
  test $# -gt 0 || set -- ${MUTTRC:-"$HOME/.muttrc"}
  test $# -gt 1 || set -- "$1" ${MUTTRC_MAILBOXES:-"$1"}

  local folder
  folder=$( grep '^set folder=' $1 | sed 's/.*"\([^"]*\)"$/\1/')

  ! grep -q '^mailboxes ' $2 || {
    grep '^mailboxes ' $2 | sed \
        -e 's/mailboxes//' \
        -e 's# + # "'"$folder"'" #' \
        -e 's#"+#"'"$folder/"'#g' \
        -e 's/ "\([^"]*\)"/\1\n/g' |
            while read -r path
            do test -n "$path" || continue
                eval "echo $path/new"; done
  }
}

## Battery/power status

battery ()
{
  charge-left-unconnected
}

power-connected ()
{
  acpi -V | grep '^Adapter ' | grep -q ' on-line$'
}

battery-charging ()
{
  acpi | cut -d' ' -f3 | grep -q '^Charging'
}

battery-discharging ()
{
  acpi | cut -d' ' -f3 | grep -q '^Discharging'
}

# Display battery charge when running on battery,
# or AC and level indicator when charging. Otherwise nothing.
charge-left-unconnected ()
{
  # shellcheck disable=SC2015
  power-connected && {

    battery-charging && {

      # Show charging AC indicator and current capacity level
      test "${NERD_FONT:-1}" != "0" && {
        battery-charge-icon-"${NERD_FONT_BAT:-mdi}"
        printf ' '
        local nerd_font_codename=nf_${NERD_FONT_AC:-mdi}_plug
        echo -en "${!nerd_font_codename}"

      } || {
        printf '%s%%' "$(battery-charge)"
        printf ' '
        printf AC
      }

    } || {

      ! battery-discharging || {

        # Detect forced discharge (while on AC) as well
        test "${NERD_FONT:-1}" != "0" && {
          battery-charge-icon-"${NERD_FONT_BAT:-mdi}"
        } || {
          printf '%s%%' "$(battery-charge)"
        }
      }
    }

  } || {

    # Show battery capacity level
    test "${NERD_FONT:-1}" != "0" && {
      battery-charge-icon-"${NERD_FONT_BAT:-mdi}"
    } || {
      printf '%s%%' "$(battery-charge)"
    }
  }
}

battery-charges ()
{
  acpi | cut -d, -f2
}

# Print total charge in procent
battery-charge-total ()
{
  local x c=0
  for x in $(seq 0 $(( ${NUM_BAT?} - 1 )))
  do
    c=$(( c + $(cat /sys/class/power_supply/BAT$x/capacity) ))
  done
  echo "$c / $NUM_BAT" | bc
  #sudo tlp-stat -b | grep Charge\ total | awk '{print $5}'
}

# Print battery charge in procent (without percent character)
battery-charge ()
{
  test ${NUM_BAT:-1} -gt 1 && {
    battery-charge-total
    return
  } || {
    battery-charges | tr -d '% '
  }
}

battery-charge-icon-fa ()
{
  local pct=$( battery-charge-total | cut -d. -f1 )
  if test $pct -lt 25
  then printf $nf_fa_battery_0
  elif test $pct -lt 50
  then printf $nf_fa_battery_1
  elif test $pct -lt 75
  then printf $nf_fa_battery_2
  elif test $pct -lt 100
  then printf $nf_fa_battery_3
  else printf $nf_fa_battery_4
  fi
}

battery-charge-icon-mdi ()
{
  local pct=$( battery-charge | cut -d. -f1 )
  if test $pct -lt 20
  then printf $nf_mdi_battery_10
  elif test $pct -lt 30
  then printf $nf_mdi_battery_20
  elif test $pct -lt 40
  then printf $nf_mdi_battery_30
  elif test $pct -lt 50
  then printf $nf_mdi_battery_40
  elif test $pct -lt 60
  then printf $nf_mdi_battery_50
  elif test $pct -lt 70
  then printf $nf_mdi_battery_60
  elif test $pct -lt 80
  then printf $nf_mdi_battery_70
  elif test $pct -lt 90
  then printf $nf_mdi_battery_80
  elif test $pct -lt 100
  then printf $nf_mdi_battery_90
  else printf $nf_mdi_battery
  fi
}


## SystemD status

# Short description of SystemD (is-system-running in manual)
systemd-status-text ()
{
  systemctl is-system-running | tr -d ' \n'
}

# Icon, or description and fail-count but only if not running
systemd-short ()
{
  test $# -gt 0 || set -- $(systemd-status-text)

  local msg
  test "${NERD_FONT:-1}" != "0" && {
    msg=$(systemd-status-icon-${NERD_FONT_STATUS:-fa} "$1")
  } ||
    msg="$1"

  test "$1" != "running" &&
      printf "$msg(%s)" $(systemd-count-failed) ||
      printf "$msg"
}

systemd-count-failed ()
{
  systemctl list-units | grep -c ' failed '
}


nf_fa_check='\Uf00c'
nf_fa_exclamation='\Uf12a'
nf_fa_delicious='\Uf1a5'
nf_fa_exclamation_circle='\Uf06a'
nf_fa_exclamation_triangle='\Uf071'
nf_fa_flash='\Uf0e7'
nf_fa_plug='\Uf1e6'
nf_fa_gear='\Uf013'

nf_fa_battery_0='\Uf244'
nf_fa_battery_1='\Uf243'
nf_fa_battery_2='\Uf242'
nf_fa_battery_3='\Uf241'
nf_fa_battery_4='\Uf240'

nf_mdi_email='\Uf6ed'
nf_mdi_email_outline='\Uf6ef'
nf_mdi_email_variant='\Ufaef'
nf_mdi_mailbox='\Ufbec'
nf_mdi_power_plug='\Ufba3'
nf_mdi_plug=$nf_mdi_power_plug
nf_mdi_power_plug_off='\Ufba4'
nf_mdi_battery='\Uf578'
nf_mdi_battery_10='\Uf579'
nf_mdi_battery_20='\Uf57a'
nf_mdi_battery_30='\Uf57b'
nf_mdi_battery_40='\Uf57c'
nf_mdi_battery_50='\Uf57d'
nf_mdi_battery_60='\Uf57e'
nf_mdi_battery_70='\Uf57f'
nf_mdi_battery_80='\Uf580'
nf_mdi_battery_90='\Uf581'

nf_oct_email='\Uf42f'
nf_oct_alert='\Uf421'
nf_oct_check='\Uf42e'
nf_oct_circle_slash='\Uf468'
nf_oct_clock='\Uf43a'
nf_oct_eye='\Uf441'
nf_oct_gear='\Uf443'
nf_oct_heart='\U2665'
nf_oct_issue_openend='\Uf41d'
nf_oct_lock='\Uf456'
nf_oct_light_bulb='\Uf400'
nf_oct_mute='\Uf466'
nf_oct_plug='\Uf492'
nf_oct_pulse='\Uf469'
nf_oct_rss='\Uf428'
nf_oct_shield='\Uf49c'
nf_oct_star='\Uf41e'
nf_oct_stop='\Uf46e'
nf_oct_x='\Uf467'
nf_oct_zap='\U26a1'


systemd-status-icon-oct ()
{
  test $# -gt 0 || set -- "$(systemd-status-text)"
  case "$1" in

    initializing | \
    starting ) printf $nf_oct_zap ;;
    running ) printf $nf_oct_check ;;
    #degraded ) ;;
    maintenance ) printf $nf_oct_gear ;;
    stopping ) printf $nf_oct_stop ;;
    offline ) printf $nf_oct_circle_slash ;;
    unknown ) printf $nf_oct_x ;;

    * ) printf $nf_oct_alert ;;
  esac
}

systemd-status-icon-fa ()
{
  test $# -gt 0 || set -- "$(systemd-status-text)"
  case "$1" in

    initializing | \
    starting ) printf $nf_fa_flash ;;
    running ) printf $nf_fa_check ;;
    maintenance ) printf $nf_fa_gear ;;

    * ) printf $nf_fa_exclamation_triangle ;;
  esac
}

"$@"
#
