#!/bin/sh

#echo $(uptime | \
#  sed 's/^[0-9\:]*\ \(.*\)\ [0-9]*\ users..load.averages\:\(.*\)$/\1\2/')

#echo $(uptime | sed 's/^\([^,]*\(,[^,]*\)\?\),\ \([^,]*\).*load[^0-9]*\(.*\)$/\'"$1"'/')

echo $(uptime | sed 's/^\(.*\),\ *\([0-9]*\ user[s]*\).*load[^0-9]*\(.*\)$/\'$1'/')


