#!/usr/bin/env bash


tb_dckr_load()
{
  ANNEX_LOCAL=$(realpath /srv/annex-local/)
  DCKR_V_LOCAL=$(realpath /srv/docker-volumes-local/)
  DCKR_V_SRC_24_2=$(realpath /srv/src-24-2-notus/)
  DCKR_V_PROJECT_24_2=$(realpath /srv/project-24-2-notus/)
  DCKR_V_SCM_GIT_24_2=$(realpath /srv/scm-git-24-2-notus/)
  TOKENS_D=$(realpath ~/.local/etc/tokens.d/)

  TB_DATA=$(realpath $DCKR_V_LOCAL/treebox/)
  TB_HOME=$TB_DATA/home
  TB_INT=$TB_HOME/bin

  #true "${DOCKER_IMAGE:=bvberkum/treebox}"

  true "${DOCKER_IMAGE:=bvberkum/sandbox}" # testing u-s CI
  true "${DOCKER_TAG:=dev}"
  true "${IMAGE:="$DOCKER_IMAGE:$DOCKER_TAG"}"
  true "${LOCAL:=local/$(basename $DOCKER_IMAGE):$DOCKER_TAG}"
}

tb_dckr_list()
{
  test $# -gt 0 || set -- {/home,/src-gh}
  ls -la $TB_DATA$1
}

tb_dckr_edit()
{
  test $# -eq 0 && {
      $EDITOR $0 $TB_DATA/home/bin/treebox
    } || {
      $EDITOR $TB_DATA/home/bin/$1
    }
}

tb_dckr_update()
{
  docker pull $IMAGE    
  tb_dckr_create
}

tb_dckr_create()
{
  docker rm -f treebox-amend
  docker run -u root --name treebox-amend $IMAGE \
      bash -c 'echo "%treebox ALL=NOPASSWD:ALL">/etc/sudoers.d/amend && chown 0 /etc/sudoers.d/amend'
  docker commit treebox-amend $LOCAL
  docker rm -f treebox-amend
}

tb_dckr_bash() { tb_dckr_run "$@" ; }
tb_dckr_run()
{
  test $# -gt 0 || set -- bash -li

  docker run \
    -ti --rm \
    --env EDITOR=vim \
    -w /home/treebox \
    --volume $TOKENS_D:/home/treebox/.local/etc/tokens.d \
    --volume $HOME/.alias:/home/treebox/.alias \
    --volume $TB_HOME/.bash_history:/home/treebox/.bash_history \
    --volume $TB_HOME/.bash_profile:/home/treebox/.bash_profile \
    --volume $TB_HOME/.bash_logout:/home/treebox/.bash_logout \
    --volume $TB_HOME/.gitconfig:/home/treebox/.gitconfig \
    --volume $TB_HOME/bin:/home/treebox/bin \
    --volume $ANNEX_LOCAL:/srv/annex-local \
    --volume $DCKR_V_LOCAL:/srv/docker-volumes-local \
    --volume $DCKR_V_SRC_24_2:/srv/src-24-2-notus \
    --volume $DCKR_V_PROJECT_24_2:/srv/project-24-2-notus \
    --volume $DCKR_V_SCM_GIT_24_2:/srv/scm-git-24-2-notus \
    --volume $(realpath /etc/localtime):/etc/localtime \
                                      $IMAGE "$@"
}

tb_dckr_dev()
{
  test $# -gt 0 || set -- bash ./sh-ci

  docker run \
    -ti --rm \
    --env EDITOR=vim \
    -u treebox \
    -w /home/treebox/project/$(basename $PWD) \
    --volume /var/run/docker.sock:/var/run/docker.sock \
    --volume $(pwd -P):/home/treebox/project/$(basename $PWD) \
    --volume $TOKENS_D:/home/treebox/.local/etc/tokens.d \
    --volume $HOME/.alias:/home/treebox/.alias \
    --volume $TB_HOME/.bash_history:/home/treebox/.bash_history \
    --volume $TB_HOME/.bash_profile:/home/treebox/.bash_profile \
    --volume $TB_HOME/.bash_logout:/home/treebox/.bash_logout \
    --volume $TB_HOME/.gitconfig:/home/treebox/.gitconfig \
    --volume $TB_HOME/bin:/home/treebox/bin \
    --volume $ANNEX_LOCAL:/srv/annex-local \
    --volume $DCKR_V_LOCAL:/srv/docker-volumes-local \
    --volume $DCKR_V_SRC_24_2:/srv/src-24-2-notus \
    --volume $DCKR_V_PROJECT_24_2:/srv/project-24-2-notus \
    --volume $DCKR_V_SCM_GIT_24_2:/srv/scm-git-24-2-notus \
    --volume $(realpath /etc/localtime):/etc/localtime \
                                      $LOCAL "$@"
}

tb_dckr_projects()
{
  false
}

tb_dckr_help()
{
  cat <<EOM
Treebox single-use container (external)

  run [<cmd=bash -li>] - run command
  bash - see run
  projects <Cwd-Project> [<Projects...>] - Mount local ~/project names
  update - pull image
EOM
}


# Use hyphen to ignore source-exec in login shell
case "${SCRIPT_NAME="`basename -- "$0" .sh`"}" in

    -* ) ;; # Ignore when sourced into shell, cannot trigger

    # Do something for specific exec-names
    treebox ) test -z "${script_alias:-}" || return 93 # Recursion
        script_alias=treebox

        test $# -gt 0 || set -- run
        tb_dckr_load
        subcmd=$1 && shift 1 &&
        tb_dckr_$subcmd "$@"
      ;;

    ${script_alias:-} )
        true
      ;;

    * )
        false # log "No frontend for $base"
      ;;

esac

# BIN:treebox (external)
# Sync: TB-BIN:treebox-ext
