#!/usr/bin/env us-pp.bash
#
# uc-build - us-pp wrapper for building user files
#
# Copyright: (C) 2026 hari <dev@dotmpe>
#
# Distributed under terms of the MIT license.
: "${DEBUG:=0}"
: "${QUIET:=0}"
! ((DEBUG)) || {
  shopt -s extdebug
  PS4='\[\033[0m\]${BASH_SOURCE:+\[\033[34m\]$BASH_SOURCE\[\033[36m\]:\[\033[32m\]${LINENO}} \[\033[33m\]+\[\033[0m\] '
  ((QUIET)) ||
    >&2 echo "$$$-\$ $0 ${*@Q}"
}
set -euo pipefail
IFS=$' \t\n'
: "${BASH_SOURCE##*/}"
if [[ ${0##*/} == "${_%%.*}" || "${0##*/}" == "${_%%.*}".* ]]
then
  : "${_c2:=$(tput setaf 2)}"
  : "${_c3:=$(tput setaf 3)}"
  : "${NORMAL:=$(tput sgr0)}"
  . us-pp
  PATH+=:$U_S/tool/bash/part
  . us-core.inc.bash
  . us-pp.inc.bash
  . us-shell.inc.bash
  . us-str.inc.bash
  . us-use.inc.bash
  userscripts::use userscripts::core
  userscripts::use userscripts::string
  userscripts::use userscripts::preproc
  (($#)) ||
    failerr "$$ uc-build: Build script argument expected" || exit
  #_us_pp_prepfile .mpe "$1"
  >/dev/null diff -bqr "${1%.uc-build}" "${us_pp_output}" &&
    echo "${_c2}$$ uc-build:${NORMAL} OK" ||
    echo "${_c3}$$ uc-build:${NORMAL} Script updates for ${1%.uc-build}" "${us_pp_output}"

  # < "$us_pp_output" > "${1%.uc-build}" cat
  exit
fi
