#!/usr/bin/env bash
#
# us-pp - simple shell-script preproc implementation
#
# Copyright 2026 hari <dev@dotmpe>
#
# Distributed under terms of the MIT license.

: "${DEBUG:=0}"
: "${QUIET:=0}"
! ((DEBUG)) || {
  shopt -s extdebug
  PS4='\[\033[0m\]${BASH_SOURCE:+\[\033[34m\]$BASH_SOURCE\[\033[36m\]:\[\033[32m\]${LINENO}} \[\033[33m\]+\[\033[0m\] '
  ((QUIET)) ||
    >&2 echo "$$$-\$ $0 ${*@Q}"
}
set -euo pipefail
IFS=$' \t\n'

# Make app user-data driven
declare -A us_pp_{defs,def_literal}
: "${UC_DATA_DIR:=/var/local/statusdir}"
: "${us_pp_data:=$UC_DATA_DIR/pp,uc.data.bash}"
#cache_loadmaps "$us_pp_data" us_pp_{defs,def_literal,lang}
[[ ! -s $us_pp_data ]] || . "$us_pp_data"
declare -n us_pp_filter='uc_pp_prefilter["$us_pp_lang"]'
# load 'auto' completion and other command, argument and data patterns in 
# similar fashion. Probably move to main part. And setup commands to push in
# (and either process or ignore) debug, help and assert type of data here.

userscripts::preproc::gpp ()
{
: alias _us_gpp
  # Standard GPP user/meta modes for reference:
  # User mode arguments:
  # 1. macro start sequence
  # 2. macro end seq
  # 3. argument start seq
  # 4. arg separator
  # 5. arg end seq
  # 6. arg balancing stack character list
  # 7. unstack char list
  # 8. number reference string
  # 9. quote char
  gpp_default_user_mode=(
    "" "" "(" "," ")" "(" ")" "#" "\\"
  )
  # Meta-macro arguments
  # 1. macro start seq
  # 2. macro end seq
  # 3. arg start seq
  # 4. arg sep seq
  # 5. arg end seq
  # 6. arg bal stack char list
  # 7. arg bal unstack char list
  gpp_default_meta_mode=(
    "#" "\n" " " " " "\n" "(" ")"
  )
  gpp_c_compat_mode=(
    -n -U "" "" "(" "," ")" "(" ")" "#" ""
    -M "\n#\w" "\n" " " " " "\n" "" ""
    +c "/*" "*/" +c "//" "\n" +c "\\\n" ""
    +s "\"" "\"" "\\" +s "'" "'" "\\"
  )
  gpp_tex_like_mode=(
    -U "\\" "" "{" "}{" "}" "{" "}" "#" "@"
  )
  gpp_default_mode=(
    -U "${gpp_default_user_mode[@]}"
    -M "${gpp_default_meta_mode[@]}"
  )
  # Custom mode that seems to work for shell (and strips unix line comments)
  gpp_shell_mode=(
    +s "\"" "\"" "\\"
    +s "'" "'" "\\"
    +c "\n#\b" "\n"
    +c "\n#\n" ""
  )
  # Testing; could not get {% ... %} syntax to work
  gpp_jinja_mode=(
    -U "{% " " %}" "(" "," ")" "({}" "})" "#" "\""
  )
  gpp_xxx_mode=(
    -U "${default_user_mode[@]}"
    -M "{%" " %}" "%" " " "\n" "(" ")"
  )
  declare -n argv=gpp_${1}
  command gpp "${argv[@]:?}" "${@:2}"
}

userscripts::preproc::main ()
{
: alias us_pp_main
  local -a files=() gppargs=()
  local run_gpp=1 run_us_pp=1 output=0 exec=0 file first_script
  while (($#))
  do case "$1" in
    ( --gpp ) ;;
    ( --no-gpp ) run_gpp=0 ;;
    ( --no-process ) run_us_pp=0 ;;
    ( --output ) output=1 ;;
    ( --process ) ;;
    ( --exec ) exec=1 ;;
    ( --help ) userscripts::preproc::main_help "${@:2}"; return ;;
    ( -- ) false ;;
    ( --* ) userscripts::preproc::main_help "$@"; return ;;
    ( -* ) gppargs+=( "$1" ) ;;
    ( * ) [[ -f $1 ]] && files+=( "$1" ) || false
    esac && shift || break
  done
  ((${#files[*]})) ||
    failerr "$$ us-pp: Preprocessor expects input file argument" || return
  local us_pp_{input,shebang,lang,inputreal,output,linecomment}
  us_pp_linecomment="#"
  for file in "${files[@]}"; do
    if [[ ! -f "${file}" ]]
    then failerr "$$ us-pp: File input expected: ${file@Q}" || return; fi
    if ((run_us_pp))
    then _us_pp_procfile "$file" ||
        failerr "$$ us-pp: E$? processing ${file@Q}" || return
      if ! ((run_gpp)); then
        if ((output))
        then cat "$us_pp_output"
        else [[ ${first_script-} ]] || first_script=$us_pp_output; fi
      else
        _us_gpp shell_mode "${gppargs[@]}" -o "$us_pp_output.i" "$us_pp_output" ||
          failerr "$$ us-pp: E$? running gpp ${us_pp_output}" || return
        if ((output)); then
          cat "$us_pp_output.i"
        else [[ ${first_script-} ]] || first_script=$us_pp_output.i; fi; fi
    else
      _us_gpp shell_mode "${gppargs[@]}" -o "$file.i" "$file" ||
        failerr "$$ us-pp: E$? running gpp ${file}" || return
      if ((output)); then
        cat "$file.i"
      else [[ ${first_script-} ]] || first_script=$file.i; fi; fi
  done
  if ((exec))
  then chmod +x "$first_script" && exec "$first_script" "${@}"; fi
}

userscripts::preproc::main_help ()
{
  local cmd=${0##*/} sub=${1-}
  local us_pp_main_man='~ - super simple preprocessor in shell script

Usage:
    ~ [infile]
    ~ <<EOM
\#define FOO This is \
   a multiline definition.
\#define GREET(name) Hello, name!
GREET(Alice)
GREET(Bob)
\\GREET(Charly)
EOM

TODO: build-in pp main inc docstrings
'
  local -A us_pp_main_sub_man=(
    [--gpp]='Use GPP to produce script file'
    [--no-gpp]='Do not add second pass GPP'
    [--no-process]='Do not run us-pp, only GPP'
    [--output]='Output after processing'
    [--process]='Use us-pp to produce script from input'
    [--exec]='Execute the produced script file'
    [--help]='Shows manual or command description'
    [-*]='Argument for GPP'
    [--]='Abort argument processing. Pass rest of arguments to executed script'
    [*]='Considered as file input, abort argument processing if non-existent file'
  )
  ! (($#)) || {
    local -n _doc='us_pp_main_sub_man["$sub"]'
    [[ ${_doc:+set} ]] || sub=--$sub
    [[ ${_doc:+set} ]] || failerr "No such command $cmd ${1@Q}" || return
    echo "$cmd $sub: $_doc"
    return
  }
  echo "${us_pp_main_man//"~"/"$cmd"}"
}

: "${BASH_SOURCE##*/}"
if [[ ${0##*/} == "${_%%.*}" || "${0##*/}" == "${_%%.*}".* ]]
then

  PATH+=:$U_S/tool/bash/part
  . us-core.inc.bash
  . us-pp.inc.bash
  . us-shell.inc.bash
  . us-str.inc.bash
  . us-use.inc.bash

  userscripts::use userscripts::core
  userscripts::use userscripts::string
  userscripts::use userscripts::preproc
  us_pp_main "$@"
  exit
fi
