#!/bin/bash
cols=$(tput cols)
vpadd="$(seq $(( $(tput lines) / 8 )) | while read; do printf 'echo;'; done)"
case "$(uname)" in

  Darwin ) esc=`echo '\033'` ;;
  Linux | CYGWIN_NT-6.1 ) esc=`echo '\o33'` ;;

esac

#env_face=fraktur
#env_face=graffiti
#env_face=ogre
env_face=roman
env_face=smisome1
#env_face=whimsy
#env_face=isometric1
#env_face=isometric2
#env_face=isometric3
#env_face=isometric4
env_face=cosmike
#env_face=cosmic
#env_face=larry3d
#env_face=rounded
eval \
    $vpadd

test -n "$T" || T=$TERM
#case "$T" in
#    *256color ) figlet -c -w$cols -f $env_face $ENV_NAME | lolcat -f -S 10 -p 5.0 - ;;
#    * ) printf -- "$esc[0;34m" ; figlet -c -w$cols -f $env_face $ENV_NAME ;;
#esac
#echo
eval\
    $vpadd
eval \
    $vpadd
printf -- "$esc[0;35m"
figlet -c -w$cols -f big $(date +%H:%M)
eval \
    $vpadd\
    $vpadd
echo
printf -- "$esc[1;30m"
figlet -c -w$cols -f term $(hostname) $TERM $SHELL $HISTNUM lines
echo
printf -- "$esc[0;30m"
figlet -c -w$cols -f binary $(date +%H:%M)
echo
printf -- "$esc[1;30m"
figlet -c -w$cols -f term $(uptime)
printf -- "$esc[0m"
eval $vpadd
