#!/bin/sh

: << =cut

=head1 NAME

sensors - Plugin to monitor current sensor values

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

. $MUNIN_LIBDIR/plugins/plugin.sh

if [ "$1" = "autoconf" ]; then
	echo yes
	exit 0
fi

if [ "$1" = "config" ]; then
    echo "graph_title DM Temperature Sensors"
    echo "graph_info Output of lm-sensors (temperature only)"
    echo "graph_args --base 1000 -l 0"
    echo "graph_vlabel temperature celcius"
    echo "graph_category hardware"
    interface_id=
    sensor_nr=
    sensors -u | grep -v Adapter | while read line
    do
        [ -z "$line" ] && {
            interface_id=
        } || [ -z "$interface_id" ] && {
            interface_label=`echo $line`
            interface_id=`echo $line|sed 's/-/_/g'`
        } || [ -z "`echo $line|grep input|grep temp`" ] || {
            sensor_nr=`echo $line|sed 's/^.*temp\([0-9]\+\).*$/\1/g'`
            echo -n $interface_id"_"$line | sed 's/_input//g'  | sed 's/:\ [0-9\.]*$/.label /g' 
            echo $interface_label temp$sensor_nr
            echo $interface_id"_"$line | sed 's/_input//g'  | sed 's/:\ [0-9\.]*$/.type GAUGE/g'
        }
    done
	exit 0
fi


interface_id=
sensors -u | grep -v Adapter | while read line
do
    [ -z "$line" ] && {
        interface_id=
    } || [ -z "$interface_id" ] && {
		interface_id=`echo $line|sed 's/-/_/g'`
    } || [ -z "`echo $line|grep input|grep temp`" ] || {
    	
        echo $interface_id"_"$line | sed 's/_input//g' | sed 's/\:\ /.value /g'
    }
done

#DATA=`sensors -u`
#TEMP1=`echo $DATA | grep 'temp1_input' | sed 's/^.*temp1_input:\ \([0-9\\.]*\).*$/\1/'`
#TEMP1_CRIT=`echo $DATA | grep 'temp1_crit' | sed 's/^.*temp1_crit:\ \([0-9\\.]*\).*$/\1/'`
#echo "temp1.value $TEMP1"
#echo "temp1.critical $TEMP1_CRIT"

