#!/bin/bash

: << =cut

=head1 NAME

sensors - Plugin to monitor current sensor values

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

. $MUNIN_LIBDIR/plugins/plugin.sh

if [ "$1" = "autoconf" ]; then
	echo yes
	exit 0
fi

TYPE=$(echo $(basename $0) | sed 's/^lm_sensors_//g')
bash $MUNIN_LIBDIR/plugins/lm_sensors.sh $TYPE $1

