#!/bin/sh
#
#: << =cut
#
#=head1 NAME
#
#sensors - Plugin to monitor current sensor values
#
#=head1 MAGIC MARKERS
#
# #%# family=auto
# #%# capabilities=autoconf
#
#=cut
#
#. $MUNIN_LIBDIR/plugins/plugin.sh
#
#if [ "$1" = "autoconf" ]; then
#	echo yes
#	exit 0
#fi
#
#if [ "$1" = "config" ]; then
#	exit 0
#fi
#

DATA=`sensors -u`

TEMP1=`echo $DATA | grep 'temp1_input' | sed 's/^.*temp1_input:\ \([0-9\\.]*\).*$/\1/'`
TEMP1_CRIT=`echo $DATA | grep 'temp1_crit' | sed 's/^.*temp1_crit:\ \([0-9\\.]*\).*$/\1/'`
echo "temp1.value $TEMP1"
echo "temp1.critical $TEMP1_CRIT"
