#!/bin/bash
# This is for transmission 2.03

# XXX this is a work in progress, this munin version does
# not seem to obey the field parameter, it is always returning a pretty well
# populated report. But it does not sum the requested field, while the GUI
# displays it in the statusbar.

case $1 in

   config )
        cat <<'EOM'
graph_title Bittorrent ratios
graph_vlabel Ratio
graph_category transmission
EOM
		for T in  uploadRatio
		do
			echo -n "$T.label " | tr 'A-Z' 'a-z'
			echo $T
		done
        exit 0;;

esac

#. /usr/share/munin/plugins/transmissionbt.sh
#
##          | 
#get_file session-stats

#transmission-remote -n mpe:tr4bt0 --peers 2048
#transmission-remote -n mpe:tr4bt0 --peer-info
transmission-remote \
	-n mpe:tr4bt0 \
	--session-stats
#transmission-remote -n mpe:tr4bt0 -l --info  -t ......


