#!/bin/bash
# This is for transmission 2.03

# XXX this is a work in progress, this munin version does
# not seem to obey the field parameter, it is always returning a pretty well
# populated report. But it does not sum the requested field, while the GUI
# displays it in the statusbar.

case $1 in

   config )
        cat <<'EOM'
graph_title Bittorrent ratios
graph_vlabel Ratio
graph_category transmission
EOM
		for T in  uploadRatio
		do
			echo -n "$T.label " | tr 'A-Z' 'a-z'
			echo $T
		done
        exit 0;;

esac

. /usr/share/munin/plugins/transmissionbt.sh

#          | 
for T in   uploadRatio
do
	echo -n "$T.value " | tr 'A-Z' 'a-z'
	get_file $T 
done


